version: '3.8'

services:
  api:
    build: .
    container_name: kids-hakaton-api
    ports:
      - "8085:8085"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Moscow